import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // AI 101 sidebar - only shows AI 101 content
    ai101Sidebar: [
        'intro',
        {
            type: 'autogenerated',
            dirName: 'pre-ai-foundations'
        },
        {
            type: 'autogenerated',
            dirName: 'ai-101'
        }
    ],

    // AI 201 sidebar - only shows AI 201 content
    ai201Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'ai-201'
        }
    ],

    // Careers sidebar
    careersSidebar: [
        {
            type: 'autogenerated',
            dirName: 'ai-and-careers'
        }
    ],

    // Automation sidebar
    automationSidebar: [
        {
            type: 'autogenerated',
            dirName: 'automation'
        }
    ],

    // MCP sidebar
    mcpSidebar: [
        {
            type: 'autogenerated',
            dirName: 'model-context-protocol'
        }
    ]
};

export default sidebars;
